// Generated by auto imports
export {}
declare global {
  const createError: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.27_cac@6.7.14_db0@0.3.4_eslint@9_bb0ab150d5c5c2009aa075c7691ab781/node_modules/nuxt/dist/app/composables/error').createError
  const defineAppConfig: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.27_cac@6.7.14_db0@0.3.4_eslint@9_bb0ab150d5c5c2009aa075c7691ab781/node_modules/nuxt/dist/app/nuxt').defineAppConfig
  const defineI18nConfig: typeof import('../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__ioredi_3306de3dd05c50babb6db9106abda703/node_modules/@nuxtjs/i18n/dist/runtime/composables/index').defineI18nConfig
  const defineI18nLocale: typeof import('../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39.2_jiti@2.6.1__ioredi_3306de3dd05c50babb6db9106abda703/node_modules/@nuxtjs/i18n/dist/runtime/composables/index').defineI18nLocale
  const getRouteRules: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.27_cac@6.7.14_db0@0.3.4_eslint@9_bb0ab150d5c5c2009aa075c7691ab781/node_modules/nuxt/dist/app/composables/manifest').getRouteRules
  const setResponseStatus: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.27_cac@6.7.14_db0@0.3.4_eslint@9_bb0ab150d5c5c2009aa075c7691ab781/node_modules/nuxt/dist/app/composables/ssr').setResponseStatus
  const useAppConfig: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.27_cac@6.7.14_db0@0.3.4_eslint@9_bb0ab150d5c5c2009aa075c7691ab781/node_modules/nuxt/dist/app/config').useAppConfig
  const useRuntimeConfig: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.27_cac@6.7.14_db0@0.3.4_eslint@9_bb0ab150d5c5c2009aa075c7691ab781/node_modules/nuxt/dist/app/nuxt').useRuntimeConfig
}