// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/26/2026, 11:13:34 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/hing/Desktop/monorepo-nuxt4/packages/core/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hing/Desktop/monorepo-nuxt4/packages/core/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hing/Desktop/monorepo-nuxt4/packages/core/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hing/Desktop/monorepo-nuxt4/packages/core/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hing/Desktop/monorepo-nuxt4/packages/core/plugins/**/*.{js,ts,mjs}","/Users/hing/Desktop/monorepo-nuxt4/packages/core/composables/**/*.{js,ts,mjs}","/Users/hing/Desktop/monorepo-nuxt4/packages/core/utils/**/*.{js,ts,mjs}","/Users/hing/Desktop/monorepo-nuxt4/packages/core/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/hing/Desktop/monorepo-nuxt4/packages/core/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/hing/Desktop/monorepo-nuxt4/packages/core/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;