// Generated by auto imports
export {}
declare global {
  const createError: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.27_cac@6.7.14_db0@0.3.4_eslint@9_bb0ab150d5c5c2009aa075c7691ab781/node_modules/nuxt/dist/app/composables/error').createError
  const defineAppConfig: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.27_cac@6.7.14_db0@0.3.4_eslint@9_bb0ab150d5c5c2009aa075c7691ab781/node_modules/nuxt/dist/app/nuxt').defineAppConfig
  const getRouteRules: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.27_cac@6.7.14_db0@0.3.4_eslint@9_bb0ab150d5c5c2009aa075c7691ab781/node_modules/nuxt/dist/app/composables/manifest').getRouteRules
  const setResponseStatus: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.27_cac@6.7.14_db0@0.3.4_eslint@9_bb0ab150d5c5c2009aa075c7691ab781/node_modules/nuxt/dist/app/composables/ssr').setResponseStatus
  const useAppConfig: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.27_cac@6.7.14_db0@0.3.4_eslint@9_bb0ab150d5c5c2009aa075c7691ab781/node_modules/nuxt/dist/app/config').useAppConfig
  const useRuntimeConfig: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@parcel+watcher@2.5.6_@vue+compiler-sfc@3.5.27_cac@6.7.14_db0@0.3.4_eslint@9_bb0ab150d5c5c2009aa075c7691ab781/node_modules/nuxt/dist/app/nuxt').useRuntimeConfig
}